REM Wallet group
SET WALLET_GROUP_NAME=%SERVICES_GROUP_NAME%.Wallet
SET WALLET_GROUP_PATH=%SERVICES_GROUP_PATH%/%WALLET_GROUP_NAME%

REM [LIB] Wallet.Contract
SET WALLET_CONTRACT_NAME=%WALLET_GROUP_NAME%.Contract
SET WALLET_CONTRACT_PATH=%WALLET_GROUP_PATH%/%WALLET_CONTRACT_NAME%
SET WALLET_CONTRACT_PROJ=%WALLET_CONTRACT_PATH%/%WALLET_CONTRACT_NAME%.csproj
dotnet new classlib -o %WALLET_CONTRACT_PATH% -f netcoreapp2.1
dotnet sln %SOLUTION_PATH_FULL% add %WALLET_CONTRACT_PROJ%
dotnet add %WALLET_CONTRACT_PROJ% reference %SHARED_KERNEL_PROJ%
dotnet add %WALLET_CONTRACT_PROJ% package MediatR
dotnet add %WALLET_CONTRACT_PROJ% package Sieve

REM [LIB] Wallet.Concrete
SET WALLET_CONCRETE_NAME=%WALLET_GROUP_NAME%.Concrete
SET WALLET_CONCRETE_PATH=%WALLET_GROUP_PATH%/%WALLET_CONCRETE_NAME%
SET WALLET_CONCRETE_PROJ=%WALLET_CONCRETE_PATH%/%WALLET_CONCRETE_NAME%.csproj
dotnet new classlib -o %WALLET_CONCRETE_PATH% -f netcoreapp2.1
dotnet sln %SOLUTION_PATH_FULL% add %WALLET_CONCRETE_PROJ%
dotnet add %WALLET_CONCRETE_PROJ% reference %WALLET_CONTRACT_PROJ%
dotnet add %WALLET_CONCRETE_PROJ% package MediatR
dotnet add %WALLET_CONCRETE_PROJ% package Sieve
dotnet add %WALLET_CONCRETE_PROJ% package FluentValidation

REM [LIB] Wallet.Infrastracture
SET WALLET_INFRASTRACTURE_NAME=%WALLET_GROUP_NAME%.Infrastracture
SET WALLET_INFRASTRACTURE_PATH=%WALLET_GROUP_PATH%/%WALLET_INFRASTRACTURE_NAME%
SET WALLET_INFRASTRACTURE_PROJ=%WALLET_INFRASTRACTURE_PATH%/%WALLET_INFRASTRACTURE_NAME%.csproj
dotnet new classlib -o %WALLET_INFRASTRACTURE_PATH% -f netcoreapp2.1
dotnet sln %SOLUTION_PATH_FULL% add %WALLET_INFRASTRACTURE_PROJ%
dotnet add %WALLET_INFRASTRACTURE_PROJ% reference %WALLET_CONCRETE_PROJ% %WALLET_CONCRETE_PROJ%
dotnet add %WALLET_INFRASTRACTURE_PROJ% package Autofac 
dotnet add %WALLET_INFRASTRACTURE_PROJ% package Microsoft.EntityFrameworkCore 
dotnet add %WALLET_INFRASTRACTURE_PROJ% package Microsoft.EntityFrameworkCore.Relational 
dotnet add %WALLET_INFRASTRACTURE_PROJ% package Microsoft.EntityFrameworkCore.SqlServer

REM [PROJECT] Wallet.API
SET WALLET_API_NAME=%WALLET_GROUP_NAME%.API
SET WALLET_API_PATH=%WALLET_GROUP_PATH%/%WALLET_API_NAME%
SET WALLET_API_PROJ=%WALLET_API_PATH%/%WALLET_API_NAME%.csproj
dotnet new webapi -o %WALLET_API_PATH% -f netcoreapp2.1
dotnet sln %SOLUTION_PATH_FULL% add %WALLET_API_PROJ%
dotnet add %WALLET_API_PROJ% reference %WALLET_INFRASTRACTURE_PROJ% %SHARED_WEB_PROJ%