REM [GROUP] Exchange
SET EXCHANGE_GROUP_NAME=%SERVICES_GROUP_NAME%.Exchange
SET EXCHANGE_GROUP_PATH=%SERVICES_GROUP_PATH%/%EXCHANGE_GROUP_NAME%

REM [LIB] Exchange.Contract
SET EXCHANGE_CONTRACT_NAME=%EXCHANGE_GROUP_NAME%.Contract
SET EXCHANGE_CONTRACT_PATH=%EXCHANGE_GROUP_PATH%/%EXCHANGE_CONTRACT_NAME%
SET EXCHANGE_CONTRACT_PROJ=%EXCHANGE_CONTRACT_PATH%/%EXCHANGE_CONTRACT_NAME%.csproj
dotnet new classlib -o %EXCHANGE_CONTRACT_PATH% -f netcoreapp2.1
dotnet sln %SOLUTION_PATH_FULL% add %EXCHANGE_CONTRACT_PROJ%
dotnet add %EXCHANGE_CONTRACT_PROJ% reference %SHARED_KERNEL_PROJ%
dotnet add %EXCHANGE_CONTRACT_PROJ% package MediatR

REM [LIB] Exchange.Concrete
SET EXCHANGE_CONCRETE_NAME=%EXCHANGE_GROUP_NAME%.Concrete
SET EXCHANGE_CONCRETE_PATH=%EXCHANGE_GROUP_PATH%/%EXCHANGE_CONCRETE_NAME%
SET EXCHANGE_CONCRETE_PROJ=%EXCHANGE_CONCRETE_PATH%/%EXCHANGE_CONCRETE_NAME%.csproj
dotnet new classlib -o %EXCHANGE_CONCRETE_PATH% -f netcoreapp2.1
dotnet sln %SOLUTION_PATH_FULL% add %EXCHANGE_CONCRETE_PROJ%
dotnet add %EXCHANGE_CONCRETE_PROJ% reference %EXCHANGE_CONTRACT_PROJ%
dotnet add %EXCHANGE_CONCRETE_PROJ% package MediatR

REM [LIB] Exchange.Infrastracture
SET EXCHANGE_INFRASTRACTURE_NAME=%EXCHANGE_GROUP_NAME%.Infrastracture
SET EXCHANGE_INFRASTRACTURE_PATH=%EXCHANGE_GROUP_PATH%/%EXCHANGE_INFRASTRACTURE_NAME%
SET EXCHANGE_INFRASTRACTURE_PROJ=%EXCHANGE_INFRASTRACTURE_PATH%/%EXCHANGE_INFRASTRACTURE_NAME%.csproj
dotnet new classlib -o %EXCHANGE_INFRASTRACTURE_PATH% -f netcoreapp2.1
dotnet sln %SOLUTION_PATH_FULL% add %EXCHANGE_INFRASTRACTURE_PROJ%
dotnet add %EXCHANGE_INFRASTRACTURE_PROJ% reference %EXCHANGE_CONCRETE_PROJ% %EXCHANGE_CONTRACT_PROJ%
dotnet add %EXCHANGE_INFRASTRACTURE_PROJ% package Autofac
dotnet add %EXCHANGE_INFRASTRACTURE_PROJ% package Microsoft.EntityFrameworkCore 
dotnet add %EXCHANGE_INFRASTRACTURE_PROJ% package Microsoft.EntityFrameworkCore.Relational 
dotnet add %EXCHANGE_INFRASTRACTURE_PROJ% package Microsoft.EntityFrameworkCore.SqlServer

REM [PROJECT] Exchange.API
SET EXCHANGE_API_NAME=%EXCHANGE_GROUP_NAME%.API
SET EXCHANGE_API_PATH=%EXCHANGE_GROUP_PATH%/%EXCHANGE_API_NAME%
SET EXCHANGE_API_PROJ=%EXCHANGE_API_PATH%/%EXCHANGE_API_NAME%.csproj
dotnet new webapi -o %EXCHANGE_API_PATH% -f netcoreapp2.1
dotnet sln %SOLUTION_PATH_FULL% add %EXCHANGE_API_PROJ%
dotnet add %EXCHANGE_API_PROJ% reference %EXCHANGE_INFRASTRACTURE_PROJ% %SHARED_WEB_PROJ%