REM [PROJECT] Presentation.Web
SET PRESENTATION_WEB_NAME=%PRESENTATION_GROUP_NAME%.Web
SET PRESENTATION_WEB_PATH=%PRESENTATION_GROUP_PATH%/%PRESENTATION_WEB_NAME%
SET PRESENTATION_WEB_PROJ=%PRESENTATION_WEB_PATH%/%PRESENTATION_WEB_NAME%.csproj
SET PRESENTATION_WEB_REPO_URL=%REPO_URL%/%PRESENTATION_WEB_NAME%

dotnet new angular -o %PRESENTATION_WEB_PATH% -f netcoreapp2.1
dotnet sln %SOLUTION_PATH_FULL% add %PRESENTATION_WEB_PROJ%
dotnet add %PRESENTATION_WEB_PROJ% reference %SHARED_WEB_PROJ%

RMDIR "%PRESENTATION_WEB_PATH%/ClientApp" /s /q